"""Element tags whose DDI 3.3 content model permits ``r:Label``.

Generated from the XSDs. Consumed by the ``ddi.maintainable.labels``
lint rule to tell an item that is *missing* a label from one that
cannot carry a label at all -- ``l:Code`` is Identifiable rather than
Maintainable and has no ``r:Label`` slot, but carries the
Agency/ID/Version that a duck-type would match on.

Regenerate with: python -m codegen.generate_model_bases
"""

from __future__ import annotations

from typing import Final

TAGS_ALLOWING_LABEL: Final[frozenset[str]] = frozenset(
    {
        "{ddi:archive:3_3}Access",
        "{ddi:archive:3_3}Archive",
        "{ddi:archive:3_3}DefaultAccess",
        "{ddi:archive:3_3}OrganizationGroup",
        "{ddi:archive:3_3}OrganizationScheme",
        "{ddi:archive:3_3}VersionDistinction",
        "{ddi:comparative:3_3}CategoryMap",
        "{ddi:comparative:3_3}Comparison",
        "{ddi:comparative:3_3}ConceptMap",
        "{ddi:comparative:3_3}ManagedItemMap",
        "{ddi:comparative:3_3}QuestionMap",
        "{ddi:comparative:3_3}RepresentationMap",
        "{ddi:comparative:3_3}UniverseMap",
        "{ddi:comparative:3_3}VariableMap",
        "{ddi:conceptualcomponent:3_3}Concept",
        "{ddi:conceptualcomponent:3_3}ConceptGroup",
        "{ddi:conceptualcomponent:3_3}ConceptScheme",
        "{ddi:conceptualcomponent:3_3}ConceptualComponent",
        "{ddi:conceptualcomponent:3_3}ConceptualVariable",
        "{ddi:conceptualcomponent:3_3}ConceptualVariableGroup",
        "{ddi:conceptualcomponent:3_3}ConceptualVariableScheme",
        "{ddi:conceptualcomponent:3_3}GeographicLocationGroup",
        "{ddi:conceptualcomponent:3_3}GeographicLocationScheme",
        "{ddi:conceptualcomponent:3_3}GeographicStructureGroup",
        "{ddi:conceptualcomponent:3_3}GeographicStructureScheme",
        "{ddi:conceptualcomponent:3_3}SubUniverseClass",
        "{ddi:conceptualcomponent:3_3}UnitType",
        "{ddi:conceptualcomponent:3_3}UnitTypeGroup",
        "{ddi:conceptualcomponent:3_3}UnitTypeScheme",
        "{ddi:conceptualcomponent:3_3}Universe",
        "{ddi:conceptualcomponent:3_3}UniverseGroup",
        "{ddi:conceptualcomponent:3_3}UniverseScheme",
        "{ddi:datacollection:3_3}CategoryDomain",
        "{ddi:datacollection:3_3}CodeDomain",
        "{ddi:datacollection:3_3}CognitiveExpertReviewActivity",
        "{ddi:datacollection:3_3}CognitiveInterviewActivity",
        "{ddi:datacollection:3_3}CollectionEvent",
        "{ddi:datacollection:3_3}ComputationItem",
        "{ddi:datacollection:3_3}ContentReviewActivity",
        "{ddi:datacollection:3_3}ControlConstruct",
        "{ddi:datacollection:3_3}ControlConstructGroup",
        "{ddi:datacollection:3_3}ControlConstructScheme",
        "{ddi:datacollection:3_3}CreateSummary",
        "{ddi:datacollection:3_3}DataCaptureDevelopment",
        "{ddi:datacollection:3_3}DataCollection",
        "{ddi:datacollection:3_3}DateTimeDomain",
        "{ddi:datacollection:3_3}DateTimeDomainReference",
        "{ddi:datacollection:3_3}DevelopmentActivity",
        "{ddi:datacollection:3_3}DevelopmentActivityGroup",
        "{ddi:datacollection:3_3}DevelopmentActivityScheme",
        "{ddi:datacollection:3_3}DevelopmentImplementation",
        "{ddi:datacollection:3_3}DevelopmentPlan",
        "{ddi:datacollection:3_3}DevelopmentResults",
        "{ddi:datacollection:3_3}DevelopmentStep",
        "{ddi:datacollection:3_3}DistributionDomain",
        "{ddi:datacollection:3_3}FocusGroupActivity",
        "{ddi:datacollection:3_3}GeographicDomain",
        "{ddi:datacollection:3_3}GeographicLocationCodeDomain",
        "{ddi:datacollection:3_3}GeographicStructureCodeDomain",
        "{ddi:datacollection:3_3}IfThenElse",
        "{ddi:datacollection:3_3}Instruction",
        "{ddi:datacollection:3_3}InstructionGroup",
        "{ddi:datacollection:3_3}Instrument",
        "{ddi:datacollection:3_3}InstrumentGroup",
        "{ddi:datacollection:3_3}InstrumentScheme",
        "{ddi:datacollection:3_3}InterviewerInstructionScheme",
        "{ddi:datacollection:3_3}LocationDomain",
        "{ddi:datacollection:3_3}Loop",
        "{ddi:datacollection:3_3}MeasurementConstruct",
        "{ddi:datacollection:3_3}MeasurementGroup",
        "{ddi:datacollection:3_3}MeasurementItem",
        "{ddi:datacollection:3_3}MeasurementScheme",
        "{ddi:datacollection:3_3}Methodology",
        "{ddi:datacollection:3_3}MissingValuesDomainReference",
        "{ddi:datacollection:3_3}NominalDomain",
        "{ddi:datacollection:3_3}NumericDomain",
        "{ddi:datacollection:3_3}NumericDomainReference",
        "{ddi:datacollection:3_3}PretestActivity",
        "{ddi:datacollection:3_3}ProcessingEvent",
        "{ddi:datacollection:3_3}ProcessingEventGroup",
        "{ddi:datacollection:3_3}ProcessingEventScheme",
        "{ddi:datacollection:3_3}ProcessingInstructionGroup",
        "{ddi:datacollection:3_3}ProcessingInstructionScheme",
        "{ddi:datacollection:3_3}QuestionBlock",
        "{ddi:datacollection:3_3}QuestionConstruct",
        "{ddi:datacollection:3_3}QuestionGrid",
        "{ddi:datacollection:3_3}QuestionGroup",
        "{ddi:datacollection:3_3}QuestionItem",
        "{ddi:datacollection:3_3}QuestionScheme",
        "{ddi:datacollection:3_3}RankingDomain",
        "{ddi:datacollection:3_3}RepeatUntil",
        "{ddi:datacollection:3_3}RepeatWhile",
        "{ddi:datacollection:3_3}ResponseDomainReference",
        "{ddi:datacollection:3_3}Roster",
        "{ddi:datacollection:3_3}Sample",
        "{ddi:datacollection:3_3}SampleFrame",
        "{ddi:datacollection:3_3}SampleFrameAccess",
        "{ddi:datacollection:3_3}SampleStep",
        "{ddi:datacollection:3_3}SamplingInformationGroup",
        "{ddi:datacollection:3_3}SamplingInformationScheme",
        "{ddi:datacollection:3_3}SamplingPlan",
        "{ddi:datacollection:3_3}SamplingStage",
        "{ddi:datacollection:3_3}ScaleDomain",
        "{ddi:datacollection:3_3}ScaleDomainReference",
        "{ddi:datacollection:3_3}Sequence",
        "{ddi:datacollection:3_3}Split",
        "{ddi:datacollection:3_3}SplitJoin",
        "{ddi:datacollection:3_3}StatementItem",
        "{ddi:datacollection:3_3}TextDomain",
        "{ddi:datacollection:3_3}TextDomainReference",
        "{ddi:datacollection:3_3}TranslationActivity",
        "{ddi:ddiprofile:3_3}DDIProfile",
        "{ddi:logicalproduct:3_3}BaseLogicalProduct",
        "{ddi:logicalproduct:3_3}Category",
        "{ddi:logicalproduct:3_3}CategoryGroup",
        "{ddi:logicalproduct:3_3}CategoryScheme",
        "{ddi:logicalproduct:3_3}ClassificationCorrespondenceTable",
        "{ddi:logicalproduct:3_3}ClassificationFamily",
        "{ddi:logicalproduct:3_3}ClassificationIndex",
        "{ddi:logicalproduct:3_3}ClassificationItem",
        "{ddi:logicalproduct:3_3}ClassificationLevel",
        "{ddi:logicalproduct:3_3}ClassificationSeries",
        "{ddi:logicalproduct:3_3}CodeList",
        "{ddi:logicalproduct:3_3}CodeListGroup",
        "{ddi:logicalproduct:3_3}CodeListScheme",
        "{ddi:logicalproduct:3_3}CoordinateRegion",
        "{ddi:logicalproduct:3_3}DataRelationship",
        "{ddi:logicalproduct:3_3}LogicalProduct",
        "{ddi:logicalproduct:3_3}LogicalRecord",
        "{ddi:logicalproduct:3_3}NCube",
        "{ddi:logicalproduct:3_3}NCubeGroup",
        "{ddi:logicalproduct:3_3}NCubeScheme",
        "{ddi:logicalproduct:3_3}RecordRelationship",
        "{ddi:logicalproduct:3_3}RepresentedVariable",
        "{ddi:logicalproduct:3_3}RepresentedVariableGroup",
        "{ddi:logicalproduct:3_3}RepresentedVariableScheme",
        "{ddi:logicalproduct:3_3}StatisticalClassification",
        "{ddi:logicalproduct:3_3}Variable",
        "{ddi:logicalproduct:3_3}VariableGroup",
        "{ddi:logicalproduct:3_3}VariableScheme",
        "{ddi:physicaldataproduct:3_3}PhysicalDataProduct",
        "{ddi:physicaldataproduct:3_3}PhysicalStructure",
        "{ddi:physicaldataproduct:3_3}PhysicalStructureGroup",
        "{ddi:physicaldataproduct:3_3}PhysicalStructureScheme",
        "{ddi:physicaldataproduct:3_3}RecordLayoutGroup",
        "{ddi:physicaldataproduct:3_3}RecordLayoutScheme",
        "{ddi:physicalinstance:3_3}PhysicalInstanceGroup",
        "{ddi:reusable:3_3}AlternateCoordinateSystem",
        "{ddi:reusable:3_3}AlternateObject",
        "{ddi:reusable:3_3}AlternateOffset",
        "{ddi:reusable:3_3}CoordinatePairs",
        "{ddi:reusable:3_3}Embargo",
        "{ddi:reusable:3_3}GeographicLocation",
        "{ddi:reusable:3_3}GeographicStructure",
        "{ddi:reusable:3_3}InformationClassification",
        "{ddi:reusable:3_3}LifecycleEvent",
        "{ddi:reusable:3_3}ManagedDateTimeRepresentation",
        "{ddi:reusable:3_3}ManagedMissingValuesRepresentation",
        "{ddi:reusable:3_3}ManagedNumericRepresentation",
        "{ddi:reusable:3_3}ManagedRepresentationGroup",
        "{ddi:reusable:3_3}ManagedRepresentationScheme",
        "{ddi:reusable:3_3}ManagedScaleRepresentation",
        "{ddi:reusable:3_3}ManagedTextRepresentation",
        "{ddi:reusable:3_3}NumberRange",
        "{ddi:reusable:3_3}OtherMaterialGroup",
        "{ddi:reusable:3_3}OtherMaterialScheme",
        "{ddi:reusable:3_3}QualityScheme",
        "{ddi:reusable:3_3}QualityStandard",
        "{ddi:reusable:3_3}QualityStandardGroup",
        "{ddi:reusable:3_3}QualityStatement",
        "{ddi:reusable:3_3}QualityStatementGroup",
        "{ddi:reusable:3_3}Range",
        "{ddi:reusable:3_3}RankingRange",
        "{ddi:reusable:3_3}ScaleDimension",
    }
)


# The namespaces the table above describes. A tag outside them is not
# 'known to have no label slot', it is simply not described here -- which
# is the difference between a DDI type and a downstream subclass carrying
# its own namespace. Derived from the schema set rather than from the tags
# above, because a namespace whose elements all lack a label slot still
# belongs here.
SCHEMA_NAMESPACES: Final[frozenset[str]] = frozenset(
    {
        "ddi:archive:3_3",
        "ddi:comparative:3_3",
        "ddi:conceptualcomponent:3_3",
        "ddi:datacollection:3_3",
        "ddi:dataset:3_3",
        "ddi:ddiprofile:3_3",
        "ddi:group:3_3",
        "ddi:instance:3_3",
        "ddi:logicalproduct:3_3",
        "ddi:physicaldataproduct:3_3",
        "ddi:physicaldataproduct_ncube_inline:3_3",
        "ddi:physicaldataproduct_ncube_normal:3_3",
        "ddi:physicaldataproduct_ncube_tabular:3_3",
        "ddi:physicaldataproduct_proprietary:3_3",
        "ddi:physicalinstance:3_3",
        "ddi:reusable:3_3",
        "ddi:studyunit:3_3",
    }
)
