from collections.abc import Iterator, MutableMapping
from typing import Any, Protocol, runtime_checkable

@runtime_checkable
class Element(Protocol):
    tag: Any
    attrib: MutableMapping[str, str]
    text: str | None
    tail: str | None

    def __iter__(self) -> Iterator[Element]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Element: ...
    def __contains__(self, item: object) -> bool: ...
    def append(self, subelement: Element) -> None: ...
    def insert(self, index: int, subelement: Element) -> None: ...
    def remove(self, subelement: Element) -> None: ...
    def clear(self) -> None: ...
    def find(
        self, path: str, namespaces: dict[str, str] | None = ...
    ) -> Element | None: ...
    def findall(
        self, path: str, namespaces: dict[str, str] | None = ...
    ) -> list[Element]: ...
    def findtext(
        self,
        path: str,
        default: str | None = ...,
        namespaces: dict[str, str] | None = ...,
    ) -> str | None: ...
    def iter(self, tag: str | None = ...) -> Iterator[Element]: ...
    def set(self, key: str, value: str) -> None: ...
    def get(self, key: str, default: str | None = ...) -> str | None: ...
    def getprevious(self) -> Element | None: ...
    def getparent(self) -> Element | None: ...
    def getroottree(self) -> Any: ...
    def __delitem__(self, index: int | slice) -> None: ...
    def makeelement(self, tag: str, attrib: dict[str, str]) -> Element: ...

etree: Any
USING_LXML: bool
PARSER_ERRORS: tuple[type[BaseException], ...]
_LXML_NEEDS_STDLIB_SERIALIZATION: bool

XMLNS: str

def create_element(tag: str, nsmap: dict[str | None, str] | None = ...) -> Element: ...
def tostring(element: Element, *, pretty_print: bool = ...) -> str: ...
def cleanup_namespaces(
    element: Element, nsmap: dict[str | None, str] | None = ...
) -> None: ...
def parse_xml(source: Any) -> Element: ...
def fromstring(data: str | bytes | bytearray) -> Element: ...
def _serialize_with_stdlib(
    element: Element,
    *,
    pretty_print: bool,
    xml_declaration: bool,
    encoding: str,
) -> str | bytes: ...
def _normalize_empty_elements(xml: str) -> str: ...
